# Sets up the auto-test/lint repair loop for Aider per project (biggest quality lever
# for local models: generate -> test -> feed errors back -> the model repairs itself).
# Writes a project-local .aider.conf.yml with the right test/lint command per language.
# Does NOT overwrite an existing project config (only creates it if missing).
import os, sys, glob

def detect(proj):
    py = os.path.exists(os.path.join(proj,"pyproject.toml")) or os.path.exists(os.path.join(proj,"requirements.txt")) \
         or glob.glob(os.path.join(proj,"*.py")) or glob.glob(os.path.join(proj,"**","*.py"),recursive=True)
    node = os.path.exists(os.path.join(proj,"package.json"))
    has_pytests = bool(glob.glob(os.path.join(proj,"**","test_*.py"),recursive=True)
                       or glob.glob(os.path.join(proj,"**","*_test.py"),recursive=True)
                       or os.path.isdir(os.path.join(proj,"tests")))
    test_cmd=None; lint_cmd=None
    if py:
        lint_cmd="ruff check --fix"            # only active if ruff is installed (Aider handles it being absent)
        if has_pytests: test_cmd="python -m pytest -q"
    elif node:
        lint_cmd="npx eslint . --fix"
        # only a test loop if a test script exists
        try:
            import json
            with open(os.path.join(proj,"package.json"),encoding="utf-8") as f:
                if "test" in (json.load(f).get("scripts",{})): test_cmd="npm test --silent"
        except Exception: pass
    return test_cmd, lint_cmd

def main():
    if len(sys.argv)<2: return
    proj=sys.argv[1]
    override=sys.argv[2] if len(sys.argv)>2 and sys.argv[2].strip() else None
    conf=os.path.join(proj,".aider.conf.yml")
    if os.path.exists(conf):
        print("Project config already exists - left untouched.")
        return
    test_cmd, lint_cmd = detect(proj)
    if override: test_cmd=override
    lines=["# Auto-generated by OVRLKD (setup-project-coding.py) - auto-test/repair loop","auto-lint: true"]
    if lint_cmd: lines.append(f'lint-cmd: "{lint_cmd}"')
    if test_cmd:
        lines += ["auto-test: true", f'test-cmd: "{test_cmd}"']
    with open(conf,"w",encoding="utf-8") as f:
        f.write("\n".join(lines)+"\n")
    if test_cmd:
        print(f"Auto-test loop ACTIVE: '{test_cmd}'  (+ lint: {lint_cmd or 'Aider-internal'})")
    else:
        print(f"Auto-lint active ({lint_cmd or 'Aider-internal'}). No tests detected -> no test loop (you can add one later in .aider.conf.yml).")

if __name__=="__main__":
    main()
